# Generated by Django 6.1.1 on 2026-09-03 11:57

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dutch", models.CharField(max_length=200)),
                ("english", models.CharField(max_length=300)),
                ("word_type", models.CharField(blank=True, max_length=50)),
                ("audio_file", models.CharField(blank=True, max_length=255, null=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
                (
                    "chapter",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "words",
                "ordering": ["dutch"],
            },
        ),
        migrations.CreateModel(
            name="SrsState",
            fields=[
                (
                    "word",
                    models.OneToOneField(
                        db_column="word_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="srs",
                        serialize=False,
                        to="vocabulary.word",
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("ease_factor", models.FloatField(default=2.5)),
                (
                    "due_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
                ("reps", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "srs_state",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Again"), (1, "Hard"), (3, "Good"), (5, "Easy")]
                    ),
                ),
                ("reviewed_on", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="vocabulary.word",
                    ),
                ),
            ],
            options={
                "db_table": "review_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
